import { serve } from 'https://deno.land/std@0.224.0/http/server.ts';

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};
const GEMINI_KEY = Deno.env.get('GEMINI_API_KEY') || '';
const MODEL = 'gemini-2.5-flash';
const SEARCH_MODEL = 'gemini-2.5-flash';
const LIMIT = 7200;
const mem = new Map<string,{date:string,used:number}>();
function dateIndia(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function usage(userId:string){const date=dateIndia();let r=mem.get(userId);if(!r||r.date!==date){r={date,used:0};mem.set(userId,r)}const rem=Math.max(0,LIMIT-r.used);return {user_id:userId,usage_date:date,used_seconds:r.used,daily_limit_seconds:LIMIT,remaining_seconds:rem,is_limit_reached:rem<=0,allowed:rem>0,formatted_remaining:rem>=3600?`${Math.floor(rem/3600)}h ${Math.floor((rem%3600)/60)}m remaining`:rem>=60?`${Math.floor(rem/60)}m remaining`:`${rem}s remaining`}}
async function gemini(body:any){if(!GEMINI_KEY)throw new Error('Palia AI backend is not configured: GEMINI_API_KEY is missing.');const url=`https://generativelanguage.googleapis.com/v1beta/models/${body.model||MODEL}:generateContent?key=${encodeURIComponent(GEMINI_KEY)}`;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body.payload)});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`Gemini API error ${r.status}`);return d}
function extract(d:any){return d?.candidates?.[0]?.content?.parts?.filter((p:any)=>p.text).map((p:any)=>p.text).join('\n')||''}
function sources(d:any){const out:any[]=[];for(const c of d?.candidates?.[0]?.groundingMetadata?.groundingChunks||[]){if(c.web?.uri)out.push({title:c.web.title||c.web.uri,url:c.web.uri,uri:c.web.uri})}return out}
serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const b=await req.json();const userId=String(b.userId||'guest');const action=String(b.action||'chat');const u=usage(userId);if(action==='usage')return new Response(JSON.stringify({success:true,usage:u}),{headers:{...cors,'Content-Type':'application/json'}});if(!u.allowed)return new Response(JSON.stringify({success:false,isLimitReached:true,error:"Daily AI limit reached. Your 2-hour allowance resets tomorrow.",usage:u}),{status:429,headers:{...cors,'Content-Type':'application/json'}});const start=Date.now();let data:any;let prompt=String(b.message||b.query||'').trim();if(!prompt&&action!=='usage')throw new Error('Message content is required.');const system='You are Palia AI, a helpful, accurate, friendly AI assistant developed by ShanPalia. Never mention or expose the underlying model/provider name. Answer naturally and clearly.';let payload:any={contents:[],generationConfig:{temperature:0.7},systemInstruction:{parts:[{text:system}]}};if(action==='search'){payload.contents=[{role:'user',parts:[{text:prompt}]}];payload.tools=[{google_search:{}}];}else{const history=Array.isArray(b.history)?b.history:[];for(const h of history.slice(-20)){const t=String(h.text||h.content||'').trim();if(t)payload.contents.push({role:h.role==='assistant'||h.role==='model'?'model':'user',parts:[{text:t}]})}payload.contents.push({role:'user',parts:[{text:prompt}]});}data=await gemini({model:action==='search'?SEARCH_MODEL:MODEL,payload});const elapsed=Math.max(1,Math.round((Date.now()-start)/1000));const r=mem.get(userId)!;r.used=Math.min(LIMIT,r.used+elapsed);const out={success:true,text:extract(data)||'No response generated.',reply:extract(data),sources:sources(data),searchQueries:action==='search'?[prompt]:[],modelUsed:'Palia AI',usage:usage(userId)};return new Response(JSON.stringify(out),{headers:{...cors,'Content-Type':'application/json'}})}catch(e){return new Response(JSON.stringify({success:false,error:e instanceof Error?e.message:'Palia AI request failed'}),{status:400,headers:{...cors,'Content-Type':'application/json'}})}});
