import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {
  Copy,
  Check,
  Volume2,
  RefreshCw,
  Share2,
  FileText,
  ExternalLink,
  Sparkles,
  User,
  AlertCircle,
} from 'lucide-react';
import { Attachment, ChatMessage, GroundingSource } from '../../types';
import { aiService } from '../../services/aiService';

interface ChatMessageItemProps {
  message: ChatMessage;
  onRegenerate?: () => void;
  onShare?: (message: ChatMessage) => void;
  ttsVoice?: string;
}

export const ChatMessageItem: React.FC<ChatMessageItemProps> = ({
  message,
  onRegenerate,
  onShare,
  ttsVoice = 'Kore',
}) => {
  const [copied, setCopied] = useState(false);
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);
  const isAssistant = message.role === 'assistant' || message.sender === 'assistant';
  const messageBody = message.content || message.text || '';

  const handleCopy = () => {
    navigator.clipboard.writeText(messageBody);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSpeak = async () => {
    if (isPlayingAudio || !messageBody) return;
    setIsPlayingAudio(true);
    try {
      await aiService.speakText(messageBody, ttsVoice);
    } finally {
      setIsPlayingAudio(false);
    }
  };

  const formattedTime =
    typeof message.timestamp === 'number'
      ? new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      : message.timestamp;

  return (
    <div
      id={`message-${message.id}`}
      className={`py-4 sm:py-6 px-4 sm:px-6 transition-colors ${
        isAssistant ? 'bg-slate-50/70 border-y border-slate-100' : 'bg-white'
      }`}
    >
      <div className="max-w-3xl mx-auto flex gap-3 sm:gap-4 items-start">
        {/* Avatar */}
        <div className="flex-shrink-0 pt-0.5">
          {isAssistant ? (
            <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-indigo-600 to-blue-500 text-white flex items-center justify-center shadow-sm">
              <Sparkles className="w-4 h-4" />
            </div>
          ) : (
            <div className="w-8 h-8 rounded-xl bg-slate-200 text-slate-700 flex items-center justify-center shadow-sm">
              <User className="w-4 h-4" />
            </div>
          )}
        </div>

        {/* Message Content Body */}
        <div className="flex-1 min-w-0 space-y-3">
          {/* Header Role & Time */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="text-xs font-semibold text-slate-900">
                {isAssistant ? 'Palia AI' : 'You'}
              </span>
              {message.toolUsed && message.toolUsed !== 'chat' && (
                <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium bg-slate-100 text-slate-600 border border-slate-200/80 uppercase">
                  {message.toolUsed}
                </span>
              )}
            </div>
            <span className="text-[11px] text-slate-400">
              {formattedTime}
            </span>
          </div>

          {/* Attachments (if user sent images or files) */}
          {message.attachments && message.attachments.length > 0 && (
            <div className="flex flex-wrap gap-2 pt-1">
              {message.attachments.map((att) => (
                <AttachmentItem key={att.id} attachment={att} />
              ))}
            </div>
          )}

          {/* Generated Image Result (if Image AI or image generated) */}
          {message.generatedImageUrl && (
            <div className="rounded-xl overflow-hidden border border-slate-200 shadow-sm max-w-md bg-slate-100 mt-2">
              <img
                src={message.generatedImageUrl}
                alt="Generated by Palia AI"
                className="w-full h-auto object-cover max-h-96"
                referrerPolicy="no-referrer"
              />
            </div>
          )}

          {/* Markdown Text Response */}
          {messageBody && (
            <div className="prose prose-slate prose-sm sm:prose-base max-w-none text-slate-800 leading-relaxed break-words">
              <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                components={{
                  code({ node, inline, className, children, ...props }: any) {
                    const match = /language-(\w+)/.exec(className || '');
                    const codeText = String(children).replace(/\n$/, '');

                    if (!inline && (match || codeText.includes('\n'))) {
                      return (
                        <CodeBlock
                          language={match ? match[1] : 'text'}
                          code={codeText}
                        />
                      );
                    }
                    return (
                      <code
                        className="px-1.5 py-0.5 rounded bg-slate-100 text-indigo-700 font-mono text-xs font-medium border border-slate-200/80"
                        {...props}
                      >
                        {children}
                      </code>
                    );
                  },
                  table({ children }) {
                    return (
                      <div className="overflow-x-auto my-3 rounded-lg border border-slate-200">
                        <table className="min-w-full divide-y divide-slate-200 text-xs sm:text-sm">
                          {children}
                        </table>
                      </div>
                    );
                  },
                  th({ children }) {
                    return (
                      <th className="px-3 py-2 bg-slate-100 text-left font-semibold text-slate-900 border-b border-slate-200">
                        {children}
                      </th>
                    );
                  },
                  td({ children }) {
                    return (
                      <td className="px-3 py-2 border-b border-slate-100 text-slate-700">
                        {children}
                      </td>
                    );
                  },
                  a({ href, children }) {
                    return (
                      <a
                        href={href}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-indigo-600 hover:text-indigo-800 underline underline-offset-2 inline-flex items-center gap-0.5"
                      >
                        {children}
                        <ExternalLink className="w-3 h-3 inline" />
                      </a>
                    );
                  },
                  ul({ children }) {
                    return <ul className="list-disc pl-5 my-2 space-y-1">{children}</ul>;
                  },
                  ol({ children }) {
                    return <ol className="list-decimal pl-5 my-2 space-y-1">{children}</ol>;
                  },
                  blockquote({ children }) {
                    return (
                      <blockquote className="border-l-4 border-indigo-400 pl-3 py-1 my-2 bg-indigo-50/50 text-slate-700 italic rounded-r">
                        {children}
                      </blockquote>
                    );
                  },
                }}
              >
                {messageBody}
              </ReactMarkdown>
            </div>
          )}

          {/* Grounding Web Sources (if web search mode) */}
          {message.sources && message.sources.length > 0 && (
            <div className="mt-3 pt-3 border-t border-slate-200/80">
              <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 mb-2">
                <Sparkles className="w-3.5 h-3.5 text-indigo-600" />
                <span>Verified Sources ({message.sources.length})</span>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {message.sources.map((source, idx) => (
                  <a
                    key={idx}
                    href={source.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center justify-between p-2 rounded-lg bg-white border border-slate-200 hover:border-indigo-300 hover:bg-indigo-50/30 transition-all text-xs group"
                  >
                    <div className="min-w-0 flex-1 pr-2">
                      <p className="font-medium text-slate-900 truncate group-hover:text-indigo-700">
                        {source.title}
                      </p>
                      <p className="text-[10px] text-slate-400 truncate">{source.url}</p>
                    </div>
                    <ExternalLink className="w-3.5 h-3.5 text-slate-400 group-hover:text-indigo-600 flex-shrink-0" />
                  </a>
                ))}
              </div>
            </div>
          )}

          {/* Error Notice */}
          {message.error && (
            <div className="flex items-start gap-2 p-3 rounded-lg bg-rose-50 border border-rose-200 text-rose-800 text-xs">
              <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5 text-rose-600" />
              <div className="flex-1">
                <p className="font-semibold">Error generating response</p>
                <p className="mt-0.5">{message.error}</p>
              </div>
            </div>
          )}

          {/* Message Action Footer (for Assistant) */}
          {isAssistant && !message.isStreaming && (
            <div className="flex items-center gap-1 pt-2">
              <button
                onClick={handleCopy}
                className="flex items-center gap-1 px-2 py-1 rounded-md text-xs text-slate-500 hover:text-slate-900 hover:bg-slate-200/70 transition-colors"
                title="Copy response"
              >
                {copied ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-600" />
                    <span className="text-emerald-600 font-medium">Copied</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy</span>
                  </>
                )}
              </button>

              <button
                onClick={handleSpeak}
                disabled={isPlayingAudio}
                className={`flex items-center gap-1 px-2 py-1 rounded-md text-xs transition-colors ${
                  isPlayingAudio
                    ? 'text-indigo-600 bg-indigo-50 font-medium'
                    : 'text-slate-500 hover:text-slate-900 hover:bg-slate-200/70'
                }`}
                title="Listen to response"
              >
                <Volume2 className={`w-3.5 h-3.5 ${isPlayingAudio ? 'animate-pulse' : ''}`} />
                <span>{isPlayingAudio ? 'Playing...' : 'Listen'}</span>
              </button>

              {onRegenerate && (
                <button
                  onClick={onRegenerate}
                  className="flex items-center gap-1 px-2 py-1 rounded-md text-xs text-slate-500 hover:text-slate-900 hover:bg-slate-200/70 transition-colors"
                  title="Regenerate response"
                >
                  <RefreshCw className="w-3.5 h-3.5" />
                  <span>Regenerate</span>
                </button>
              )}

              {onShare && (
                <button
                  onClick={() => onShare(message)}
                  className="flex items-center gap-1 px-2 py-1 rounded-md text-xs text-slate-500 hover:text-slate-900 hover:bg-slate-200/70 transition-colors"
                  title="Share response"
                >
                  <Share2 className="w-3.5 h-3.5" />
                  <span>Share</span>
                </button>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

// Sub-component for code blocks with copy
const CodeBlock: React.FC<{ language: string; code: string }> = ({ language, code }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="my-3 rounded-xl overflow-hidden border border-slate-800 bg-slate-950 text-slate-100 font-mono text-xs shadow-md">
      <div className="flex items-center justify-between px-4 py-2 bg-slate-900/90 border-b border-slate-800">
        <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
          {language}
        </span>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1 px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 transition-colors text-[11px]"
          title="Copy code"
        >
          {copied ? (
            <>
              <Check className="w-3 h-3 text-emerald-400" />
              <span className="text-emerald-400">Copied</span>
            </>
          ) : (
            <>
              <Copy className="w-3 h-3" />
              <span>Copy code</span>
            </>
          )}
        </button>
      </div>
      <pre className="p-4 overflow-x-auto leading-relaxed text-slate-200 selection:bg-indigo-500/30">
        <code>{code}</code>
      </pre>
    </div>
  );
};

// Sub-component for displaying attachments inside messages
const AttachmentItem: React.FC<{ attachment: Attachment }> = ({ attachment }) => {
  if (attachment.type === 'image' && attachment.dataUrl) {
    return (
      <div className="relative group rounded-lg overflow-hidden border border-slate-200 w-24 h-24 bg-slate-100 shadow-2xs">
        <img
          src={attachment.dataUrl}
          alt={attachment.name}
          className="w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-slate-950/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center p-1 text-center">
          <span className="text-[9px] text-white font-medium truncate">{attachment.name}</span>
        </div>
      </div>
    );
  }

  return (
    <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-white border border-slate-200 text-slate-800 text-xs shadow-2xs">
      <FileText className="w-4 h-4 text-indigo-600 flex-shrink-0" />
      <div className="min-w-0">
        <p className="font-medium truncate max-w-[140px]">{attachment.name}</p>
        <p className="text-[10px] text-slate-400">{(attachment.size / 1024).toFixed(1)} KB</p>
      </div>
    </div>
  );
};
